name: Build and Push Docker Image to AWS

on:
  push:
    branches:
      - main  # Triggers the action when you push to the main branch
  pull_request:
    branches:
      - main  # Triggers on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # Latest stable version (v3)

    # Configure AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2  # Latest stable version (v2)
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Adjust to your desired AWS region

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1  # Latest stable version (v1)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Latest stable version (v2)

    - name: Cache Docker layers
      uses: actions/cache@v3  # Latest stable version (v3)
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and Push Docker Image to AWS
      run: |
        docker build -t clickmine-image .
        docker tag clickmine-image:latest 593793040120.dkr.ecr.us-east-1.amazonaws.com/clickmine-repo:latest
        docker push 593793040120.dkr.ecr.us-east-1.amazonaws.com/clickmine-repo:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1  # Adjust to your desired AWS region
